import test from 'node:test'
import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import sharp from 'sharp'
import { servidorPrueba, datosCliente, ficha } from './portal-helper.mjs'

const require = createRequire(import.meta.url)
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')

test('Portal: registro, aprobación, fotos, pedido, reintento, historial y móvil', { timeout: 120000 }, async (t) => {
  const { base, request, admin, sesion } = await servidorPrueba(t)
  const a = (p, m = 'GET', b) => request(p, m, b, admin)
  const p = (await a('/productos', 'POST', { nombre: 'Armario Áurea', valorVenta: 650000, stockApertura: 20 })).data
  const mesa = (await a('/productos', 'POST', { nombre: 'Mesa Origen', valorVenta: 280000, stockApertura: 20 })).data
  const tocador = (await a('/productos', 'POST', { nombre: 'Tocador Serena', valorVenta: 420000, stockApertura: 20 })).data
  for (const item of [mesa, tocador]) await a(`/portal-admin/productos/${item.id}`, 'PUT', { ...ficha, precio: item.valorVenta })
  const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) })
  t.after(() => browser.close())
  const contexto = await browser.newContext({ viewport: { width: 1440, height: 1050 }, serviceWorkers: 'block' })
  const page = await contexto.newPage()
  const errores = []
  page.on('pageerror', (e) => errores.push(e.message))
  const capturas = process.env.UI_SCREENSHOT_DIR
  if (capturas) await mkdir(capturas, { recursive: true })
  await page.goto(`${base}/catalogo/`)
  assert.equal(await page.locator('link[rel="manifest"]').count(), 0, 'El portal no instala la PWA de nómina')
  await page.getByRole('heading', { name: 'Qué bueno verte.' }).waitFor()
  if (capturas) await page.screenshot({ path: join(capturas, 'portal-acceso.png'), fullPage: true })
  await page.getByRole('button', { name: 'Solicitar acceso', exact: true }).click()
  const datos = datosCliente()
  for (const [nombre, key] of [['Nombre del negocio','negocio'], ['Nombre de contacto','contacto'], ['NIT o documento','nit'], ['Teléfono de contacto','telefono'], ['Dirección','direccion'], ['Ciudad o municipio','municipio'], ['Correo electrónico','correo'], ['Contraseña','password']]) await page.getByLabel(nombre, { exact: true }).fill(datos[key])
  await page.getByLabel('Autorizo el uso de mis datos', { exact: false }).check()
  await page.getByLabel('Quiero recibir novedades y ofertas', { exact: false }).check()
  await page.getByLabel('Autorizo confirmaciones y actualizaciones', { exact: false }).check()
  await page.getByRole('button', { name: 'Solicitar mi cuenta mayorista' }).click()
  await page.getByText('Solicitud recibida.', { exact: false }).waitFor()
  await page.getByLabel('Correo electrónico').fill(datos.correo)
  await page.getByLabel('Contraseña', { exact: true }).fill(datos.password)
  await page.getByRole('button', { name: 'Entrar al catálogo' }).click()
  await page.getByRole('alert').filter({ hasText: 'pendiente de aprobación' }).waitFor()
  // Administración en un contexto separado del cliente.
  const interno = await browser.newContext({ viewport: { width: 1440, height: 1000 }, serviceWorkers: 'block' })
  await interno.addInitScript((s) => {
    sessionStorage.setItem('nomina_token', s.token); sessionStorage.setItem('nomina_user', s.username); sessionStorage.setItem('nomina_rol', 'admin')
  }, sesion)
  const gestion = await interno.newPage()
  gestion.on('pageerror', (e) => errores.push(e.message))
  await gestion.goto(`${base}/portal-mayorista`)
  await gestion.getByRole('button', { name: 'Aprobar acceso' }).click()
  await gestion.locator('.swal2-confirm').click()
  await gestion.getByText('Cuenta actualizada', { exact: true }).waitFor()
  await gestion.getByRole('button', { name: 'Catálogo y fotografías' }).click()
  await gestion.locator('.pm-productos article').filter({ hasText: 'Armario Áurea' }).getByRole('button', { name: 'Editar ficha' }).click()
  await gestion.getByLabel('Publicar en el catálogo mayorista').check()
  await gestion.getByLabel('Categoría', { exact: true }).fill('Armarios')
  await gestion.getByLabel('Descripción comercial').fill('Una pieza cálida y funcional para completar tu colección. Producto de prueba.')
  await gestion.getByLabel('Medidas', { exact: true }).fill('120 cm × 180 cm × 45 cm')
  await gestion.getByLabel('Mínimo por color').fill('2')
  const imagen = await sharp(Buffer.from('<svg width="640" height="480"><rect width="640" height="480" fill="#e8e2d6"/><ellipse cx="320" cy="420" rx="180" ry="20" fill="#d1c6b1"/><rect x="175" y="65" width="290" height="345" rx="2" fill="#b98f60"/><rect x="188" y="77" width="128" height="317" fill="#cba779"/><rect x="326" y="77" width="126" height="317" fill="#cba779"/><path d="M300 210v30m40-30v30" stroke="#615443" stroke-width="5"/><path d="M192 410v18m256-18v18" stroke="#987349" stroke-width="10"/></svg>')).png().toBuffer()
  const detalle = await sharp(imagen).extract({ left: 165, top: 70, width: 300, height: 280 }).resize(600, 560).png().toBuffer()
  const lateral = await sharp(imagen).flop().modulate({ brightness: 0.8 }).png().toBuffer()
  await gestion.getByLabel('Fotografías del producto').setInputFiles([
    { name: 'armario-frente.png', mimeType: 'image/png', buffer: imagen },
    { name: 'armario-detalle.png', mimeType: 'image/png', buffer: detalle },
    { name: 'armario-lateral.png', mimeType: 'image/png', buffer: lateral },
  ])
  await gestion.getByAltText('Vista previa 3', { exact: true }).waitFor()
  await gestion.getByRole('button', { name: 'Usar foto 2 como portada' }).click()
  await gestion.getByRole('button', { name: 'Mover foto 1 después' }).click()
  if (capturas) {
    await gestion.getByText('Cuenta actualizada', { exact: true }).waitFor({ state: 'hidden' })
    await gestion.locator('.pm-galeria').screenshot({ path: join(capturas, 'galeria-administracion.png') })
  }
  await gestion.getByRole('button', { name: 'Guardar ficha', exact: true }).click()
  await gestion.getByText('Ficha del catálogo guardada', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Entrar al catálogo' }).click()
  await page.getByRole('heading', { name: 'Nuestra colección', exact: false }).waitFor()
  await page.getByAltText('Armario Áurea').waitFor()
  await page.getByAltText('Armario Áurea').evaluate((img) => img.decode())
  const primerSrc = await page.getByAltText('Armario Áurea').getAttribute('src')
  await page.getByRole('button', { name: 'Foto siguiente de Armario Áurea', exact: true }).click()
  assert.notEqual(await page.getByAltText('Armario Áurea').getAttribute('src'), primerSrc)
  await page.getByRole('button', { name: 'Ampliar fotos de Armario Áurea', exact: true }).click()
  const galeria = page.getByRole('dialog', { name: 'Fotos de Armario Áurea', exact: true })
  await galeria.getByText('Fotografía 2 de 3', { exact: false }).waitFor()
  await galeria.getByRole('button', { name: 'Ver fotografía 3' }).click()
  await galeria.getByAltText('Armario Áurea · fotografía 3').evaluate((img) => img.decode())
  await page.keyboard.press('ArrowLeft')
  await galeria.getByText('Fotografía 2 de 3', { exact: false }).waitFor()
  if (capturas) await page.screenshot({ path: join(capturas, 'galeria-cliente.png') })
  await page.keyboard.press('Escape')
  await galeria.waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Foto anterior de Armario Áurea', exact: true }).click()
  // Quitar una imagen conserva las otras y cancelar la edición no aplica cambios.
  const tarjeta = gestion.locator('.pm-productos article').filter({ hasText: 'Armario Áurea' })
  await tarjeta.getByRole('button', { name: 'Editar ficha' }).click()
  await gestion.getByRole('button', { name: 'Quitar foto 3', exact: true }).click()
  await gestion.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await tarjeta.getByRole('button', { name: 'Editar ficha' }).click()
  assert.equal(await gestion.locator('.pm-galeria li').count(), 3)
  await gestion.getByRole('button', { name: 'Quitar foto 3', exact: true }).click()
  await gestion.getByRole('button', { name: 'Guardar ficha', exact: true }).click()
  await gestion.getByRole('dialog', { name: 'Ficha de Armario Áurea' }).waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Actualizar catálogo', exact: true }).click()
  await page.locator('.foto-navegacion').getByText('1 / 2', { exact: true }).waitFor()
  if (capturas) await page.screenshot({ path: join(capturas, 'portal-catalogo-escritorio.png'), fullPage: true })
  assert.equal(await page.locator('.producto').count(), 3)
  await page.getByLabel('Buscar productos').fill('Áurea')
  assert.equal(await page.locator('.producto').count(), 1)
  await page.getByLabel('Buscar productos').fill('')
  await page.getByRole('button', { name: 'Agregar Armario Áurea' }).click()
  const agregado = page.getByRole('dialog', { name: '¡Producto agregado!', exact: true })
  await agregado.getByText('Agregaste', { exact: false }).waitFor()
  assert.match(await agregado.innerText(), /2 unidades/)
  assert.equal((await a('/pedidos')).data.length, 0, 'Agregar no envía ni registra un pedido')
  assert.ok(await agregado.evaluate((el) => el.contains(document.activeElement)), 'La confirmación recibe el foco')
  if (capturas) await page.screenshot({ path: join(capturas, 'producto-agregado-escritorio.png'), animations: 'disabled' })
  await agregado.getByRole('button', { name: 'Seguir eligiendo productos' }).click()
  await page.getByRole('complementary', { name: 'Resumen de tu pedido' }).getByText('2 unidades en tu pedido').waitFor()
  await page.getByRole('button', { name: 'Agregar Armario Áurea' }).click()
  await agregado.getByText('Agregaste', { exact: false }).waitFor()
  assert.match(await agregado.innerText(), /Agregaste 1 unidad/)
  assert.match(await agregado.innerText(), /3 unidades en tu pedido/)
  await agregado.getByRole('button', { name: 'Ver mi pedido y continuar' }).click()
  await page.keyboard.press('Shift+Tab')
  assert.ok(await page.locator('.carrito').evaluate((el) => el.contains(document.activeElement)), 'El foco se conserva dentro del carrito')
  await page.getByLabel('Cantidad de Armario Áurea').fill('3')
  await page.getByLabel('Dirección de entrega', { exact: true }).fill('Carrera 50 # 10-20')
  await page.getByLabel('Revisé los productos', { exact: false }).check()
  // El servidor guarda pero el navegador pierde la respuesta. El segundo envío debe recuperar el mismo pedido.
  let perderRespuesta = true
  await page.route('**/api/portal/pedidos', async (route) => {
    if (route.request().method() === 'POST' && perderRespuesta) {
      perderRespuesta = false
      await route.fetch()
      await route.abort('failed')
    } else await route.continue()
  })
  await page.getByRole('button', { name: 'Confirmar y enviar pedido' }).click()
  await page.getByRole('button', { name: 'Reintentar el mismo pedido' }).waitFor()
  assert.equal((await a('/pedidos')).data.length, 1)
  await page.reload()
  await page.getByRole('button', { name: /Ver pedido,/ }).click()
  await page.getByRole('button', { name: 'Reintentar el mismo pedido' }).click()
  await page.getByRole('heading', { name: /Recibimos tu pedido #/ }).waitFor()
  assert.equal(await page.getByRole('complementary', { name: 'Resumen de tu pedido' }).count(), 0)
  assert.equal((await a('/pedidos')).data.length, 1)
  await page.getByRole('button', { name: 'Ver mis pedidos', exact: true }).click()
  await page.getByRole('heading', { name: 'Pedido #1', exact: true }).waitFor()
  await page.getByText('Carrera 50 # 10-20', { exact: false }).waitFor()
  await gestion.goto(`${base}/pedidos`)
  await gestion.getByText('Portal mayorista', { exact: true }).waitFor()
  await gestion.locator('tbody tr').filter({ hasText: 'Portal mayorista' }).click()
  await gestion.getByText('Entrega solicitada:', { exact: false }).waitFor()
  // Cambiar contraseña y volver a entrar conserva el historial del cliente.
  await page.getByRole('button', { name: 'Mi cuenta', exact: true }).click()
  await page.getByLabel('Contraseña actual', { exact: true }).fill(datos.password)
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('ClaveNueva2026!')
  await page.getByRole('button', { name: 'Guardar contraseña' }).click()
  await page.getByText('Contraseña actualizada.', { exact: false }).waitFor()
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click()
  await page.getByRole('heading', { name: 'Qué bueno verte.' }).waitFor()
  await page.getByLabel('Correo electrónico').fill(datos.correo)
  await page.getByLabel('Contraseña', { exact: true }).fill('ClaveNueva2026!')
  await page.getByRole('button', { name: 'Entrar al catálogo' }).click()
  await page.getByRole('heading', { name: 'Nuestra colección', exact: false }).waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Ampliar fotos de Armario Áurea', exact: true }).click()
  await galeria.getByRole('button', { name: 'Fotografía siguiente' }).click()
  await galeria.getByText('Fotografía 2 de 2', { exact: false }).waitFor()
  if (capturas) await page.screenshot({ path: join(capturas, 'galeria-cliente-movil.png') })
  await galeria.getByRole('button', { name: 'Cerrar galería' }).click()
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'Sin desbordamiento horizontal en móvil')
  if (capturas) await page.screenshot({ path: join(capturas, 'portal-catalogo-movil.png'), fullPage: true })
  await page.getByRole('button', { name: 'Agregar Armario Áurea' }).click()
  await agregado.getByText('Agregaste', { exact: false }).waitFor()
  assert.ok(await agregado.evaluate((el) => { const r=el.getBoundingClientRect(); return r.left>=0 && r.right<=innerWidth && r.top>=0 && r.bottom<=innerHeight }), 'Confirmación visible en pantalla móvil')
  if (capturas) await page.screenshot({ path: join(capturas, 'producto-agregado-movil.png'), animations: 'disabled' })
  await page.keyboard.press('Escape')
  await agregado.waitFor({ state: 'hidden' })
  await page.evaluate(() => window.scrollTo(0, 0))
  const resumen = page.getByRole('complementary', { name: 'Resumen de tu pedido' })
  assert.ok(await resumen.evaluate((el) => { const r=el.getBoundingClientRect(); return r.top>=0 && r.bottom<=innerHeight }), 'Resumen siempre visible al desplazarse')
  if (capturas) await page.screenshot({ path: join(capturas, 'pedido-visible-movil.png') })
  await page.reload()
  await page.getByRole('button', { name: 'Ver y enviar mi pedido' }).click()
  if (capturas) await page.screenshot({ path: join(capturas, 'portal-pedido-movil.png'), fullPage: true })
  assert.equal(await page.getByLabel('Cantidad de Armario Áurea').inputValue(), '2')
  await page.getByRole('button', { name: 'Quitar Armario Áurea', exact: true }).click()
  await page.getByRole('button', { name: 'Cerrar pedido', exact: true }).click()
  assert.equal(await resumen.count(), 0, 'El resumen desaparece al vaciar el pedido')
  await gestion.goto(`${base}/portal-mayorista`)
  await gestion.getByRole('button', { name: 'WhatsApp', exact: true }).click()
  await gestion.getByRole('heading', { name: 'WhatsApp de tu negocio' }).waitFor()
  assert.equal(await gestion.getByRole('button', { name: 'Conectar WhatsApp', exact: true }).isDisabled(), true)
  await gestion.getByLabel('Preparar notificaciones para nuevos pedidos').check()
  await gestion.getByRole('button', { name: 'Guardar configuración' }).click()
  await gestion.getByText('Configuración guardada', { exact: true }).waitFor()
  await gestion.getByLabel('Texto de la oferta').fill('Oferta de prueba para nuestra nueva colección.')
  await gestion.getByLabel(/Muebles del Norte ·/).check()
  await gestion.getByRole('button', { name: 'Preparar vista previa' }).click()
  await gestion.getByRole('heading', { name: 'Mensaje que recibirán tus clientes' }).waitFor()
  await gestion.getByLabel('Texto de la oferta').fill('Oferta corregida de nuestra nueva colección.')
  assert.equal(await gestion.getByRole('button', { name: 'Confirmar y encolar oferta' }).count(), 0)
  await gestion.getByRole('button', { name: 'Preparar vista previa' }).click()
  await gestion.getByRole('button', { name: 'Confirmar y encolar oferta' }).click()
  await gestion.getByText('Oferta encolada.', { exact: false }).waitFor()
  await gestion.getByRole('button', { name: 'Actualizar mensajes' }).click()
  await gestion.locator('.wa-tabla').getByText('pendiente', { exact: true }).waitFor()
  await gestion.getByText('Oferta encolada.', { exact: false }).waitFor({ state: 'hidden' })
  await gestion.evaluate(() => window.scrollTo(0, 0))
  if (capturas) await gestion.screenshot({ path: join(capturas, 'whatsapp-panel.png'), fullPage: true })
  await gestion.getByRole('button', { name: 'Cancelar mensaje' }).click()
  await gestion.locator('.wa-tabla').getByText('cancelado', { exact: true }).waitFor()
  await gestion.setViewportSize({ width: 390, height: 844 })
  await gestion.getByText('Mensaje cancelado', { exact: true }).waitFor({ state: 'hidden' })
  await gestion.evaluate(() => window.scrollTo(0, 0))
  assert.ok(await gestion.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'WhatsApp sin desbordamiento horizontal en móvil')
  if (capturas) await gestion.screenshot({ path: join(capturas, 'whatsapp-panel-movil.png'), fullPage: true })
  assert.deepEqual(errores, [])
})
